version: "3.7"

services:
  server:
    build: ./server
    command: npm start
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: dummyguys
      MYSQL_DB: disney
    depends_on:
      - database

  database:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dummyguys
      MYSQL_DATABASE: disney

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: dummyguys
      PMA_HOST: database 
      PMA_USER: root
      PMA_PASSWORD: dummyguys

volumes:
  mysql-data:


